
import React, { useState } from 'react';
import { TumorClass } from '../types';
import { Icons } from '../constants';
import { useData } from '../contexts/DataContext';

const History: React.FC = () => {
  const { reports } = useData();
  const [selectedReport, setSelectedReport] = useState<any | null>(null);
  const [notification, setNotification] = useState<string | null>(null);

  const showNotification = (message: string) => {
    setNotification(message);
    setTimeout(() => setNotification(null), 3000);
  };

  const handleDownloadPDF = (report: any) => {
    import('jspdf').then(module => {
      const jsPDF = module.default;
      const doc = new jsPDF();

      // Header
      doc.setFillColor(41, 128, 185); // Blue
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.text("BreastCancerAI", 20, 25);
      doc.setFontSize(10);
      doc.text("Diagnostic Analysis Report", 150, 25);

      // Patient Info
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
      doc.text(`Patient ID: ${report.patientId}`, 20, 50);
      doc.text(`Patient Name: ${report.patientName || 'N/A'}`, 20, 60);
      doc.text(`Date: ${report.date}`, 140, 50);
      doc.text(`Report ID: ${report.id}`, 140, 60);

      // Line Divider
      doc.setDrawColor(200, 200, 200);
      doc.line(20, 70, 190, 70);

      // Results
      doc.setFontSize(16);
      doc.setTextColor(report.tumorClass === TumorClass.MALIGNANT ? 200 : 0, report.tumorClass === TumorClass.BENIGN ? 150 : 0, 0);
      doc.text(`Result: ${report.tumorClass.toUpperCase()}`, 20, 90);

      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
      doc.text(`Confidence: ${report.confidence}%`, 140, 90);

      // Findings
      doc.setFontSize(14);
      doc.text("AI Findings:", 20, 110);
      doc.setFontSize(11);
      doc.setTextColor(80, 80, 80);
      const splitText = doc.splitTextToSize(report.explanation || "No explanation provided.", 170);
      doc.text(splitText, 20, 120);

      // Recommendations
      if (report.recommendations && report.recommendations.length > 0) {
        let yPos = 120 + (splitText.length * 5) + 20;
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text("Clinical Recommendations:", 20, yPos);

        doc.setFontSize(11);
        doc.setTextColor(80, 80, 80);
        yPos += 10;
        report.recommendations.forEach((rec: string) => {
          doc.text(`• ${rec}`, 25, yPos);
          yPos += 7;
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by BreastCancerAI. This is an assistive tool and not a final diagnosis.", 20, 280);

      doc.save(`Report_${report.patientId}_${report.date}.pdf`);
      showNotification('PDF downloaded successfully!');
    });
  };

  const handleExportCSV = () => {
    if (reports.length === 0) {
      showNotification("No data to export.");
      return;
    }
    const headers = ['Analysis ID', 'Patient Name', 'Patient ID', 'Date', 'Result', 'Confidence'];
    const csvContent = [
      headers.join(','),
      ...reports.map(row => [row.id, row.patientName, row.patientId, row.date, row.tumorClass, `${row.confidence}%`].join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `oncovision-history-${Date.now()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    showNotification('CSV exported successfully!');
  };

  return (
    <div className="fade-in-up space-y-6 relative" style={{ animationDuration: '0.6s' }}>
      {/* Toast Notification */}
      {notification && (
        <div className="fixed top-6 right-6 bg-slate-900 border border-slate-700 text-white px-6 py-4 rounded-2xl shadow-2xl z-50 animate-fade-in-up flex items-center gap-3">
          <div className="w-2 h-2 rounded-full bg-blue-500 animate-pulse"></div>
          <span className="font-medium text-sm">{notification}</span>
        </div>
      )}

      {/* Report Modal */}
      {selectedReport && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-md z-50 flex items-center justify-center p-4 transition-opacity" onClick={() => setSelectedReport(null)}>
          <div className="glass-panel max-w-lg w-full p-8 animate-in zoom-in-95 duration-300 shadow-2xl" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-start mb-8 border-b border-slate-100 pb-4">
              <div>
                <h3 className="text-xl font-bold text-slate-800 tracking-tight">Analysis Details</h3>
                <p className="text-xs font-mono text-slate-500 mt-1">ID: {selectedReport.id}</p>
              </div>
              <button onClick={() => setSelectedReport(null)} className="p-2 bg-slate-50 hover:bg-slate-200 rounded-full transition-colors text-slate-500 hover:text-slate-800">
                <Icons.X size={18} />
              </button>
            </div>

            <div className="space-y-6">
              <div className="bg-slate-50/50 p-5 rounded-2xl border border-slate-100">
                <div className="grid grid-cols-2 gap-y-4 gap-x-6 text-sm">
                  <div>
                    <span className="block font-bold text-slate-400 text-[10px] uppercase tracking-widest mb-1">Patient</span>
                    <span className="font-medium text-slate-800">{selectedReport.patientName}</span>
                    <span className="block text-xs text-slate-500 mt-0.5">{selectedReport.patientId}</span>
                  </div>
                  <div>
                    <span className="block font-bold text-slate-400 text-[10px] uppercase tracking-widest mb-1">Date</span>
                    <span className="font-medium text-slate-800">{selectedReport.date}</span>
                  </div>
                  <div className="col-span-2 pt-2 border-t border-slate-200/50">
                    <span className="block font-bold text-slate-400 text-[10px] uppercase tracking-widest mb-2">Confidence Score</span>
                    <div className="flex items-center gap-3">
                      <div className="flex-1 h-2 bg-slate-200 rounded-full overflow-hidden">
                        <div className={`h-full ${selectedReport.tumorClass === TumorClass.MALIGNANT ? 'bg-red-500' : 'bg-green-500'}`} style={{ width: `${selectedReport.confidence}%` }}></div>
                      </div>
                      <span className="font-bold text-slate-800">{selectedReport.confidence.toFixed(1)}%</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className={`p-5 rounded-2xl border ${selectedReport.tumorClass === TumorClass.MALIGNANT ? 'bg-rose-50 border-rose-100' : 'bg-emerald-50 border-emerald-100'}`}>
                <span className="block font-bold text-slate-400 text-[10px] uppercase tracking-widest mb-1">Classification</span>
                <span className={`text-xl font-black tracking-tight ${selectedReport.tumorClass === TumorClass.MALIGNANT ? 'text-rose-700' : 'text-emerald-700'}`}>
                  {selectedReport.tumorClass}
                </span>
                <p className="text-sm text-slate-700 mt-2 font-medium">
                  {selectedReport.tumorClass === TumorClass.MALIGNANT
                    ? 'Automated analysis detected patterns consistent with malignancy.'
                    : 'No malignant patterns detected in the analyzed sample.'}
                </p>
                {selectedReport.explanation && (
                  <p className="text-xs text-slate-500 mt-3 italic border-t border-slate-200/50 pt-3 leading-relaxed">
                    "{selectedReport.explanation.substring(0, 150)}..."
                  </p>
                )}
              </div>
            </div>

            <div className="flex gap-3 mt-8">
              <button onClick={() => setSelectedReport(null)} className="btn-secondary flex-[0.5]">
                Close
              </button>
              <button onClick={() => handleDownloadPDF(selectedReport)} className="btn-primary flex-1 py-4 text-sm">
                <Icons.Reports size={18} />
                Download PDF
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="flex justify-between items-center sm:items-end flex-col sm:flex-row gap-4 mb-2">
        <div>
          <h1 className="text-3xl font-bold text-slate-800 tracking-tight">Analysis Archive</h1>
          <p className="text-slate-500 font-light mt-1">History of all diagnostic scans performed by your team.</p>
        </div>
        <div className="flex gap-2 relative z-10 w-full sm:w-auto">
          <button
            onClick={handleExportCSV}
            className="w-full sm:w-auto px-5 py-2.5 bg-white border border-slate-200 text-slate-700 rounded-xl text-sm font-semibold hover:bg-slate-50 hover:text-slate-900 transition-all shadow-sm flex items-center justify-center gap-2"
          >
            <Icons.Reports size={16} />
            Export CSV
          </button>
        </div>
      </div>

      <div className="glass-panel overflow-hidden border border-slate-200/60 bg-white/60 backdrop-blur-md">
        <div className="overflow-x-auto custom-scrollbar">
          <table className="w-full text-left border-collapse min-w-[800px]">
            <thead>
              <tr className="bg-slate-50/80 border-b border-slate-100">
                <th className="px-6 py-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest whitespace-nowrap">Analysis ID</th>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest">Patient Details</th>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest">Date Processed</th>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest">Diagnosis</th>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest">AI Confidence</th>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100/60">
              {reports.length > 0 ? (
                reports.map((row) => (
                  <tr key={row.id} className="hover:bg-blue-50/30 transition-colors group">
                    <td className="px-6 py-5 font-mono text-xs text-slate-500">{row.id.substring(0, 8)}...</td>
                    <td className="px-6 py-5">
                      <p className="font-bold text-slate-800 text-sm">{row.patientName}</p>
                      <p className="text-[11px] text-slate-500 mt-0.5">{row.patientId}</p>
                    </td>
                    <td className="px-6 py-5 text-slate-600 text-sm font-medium">{row.date}</td>
                    <td className="px-6 py-5">
                      <span className={`text-[10px] font-bold px-3 py-1.5 rounded-lg uppercase tracking-widest ${row.tumorClass.toUpperCase() === 'MALIGNANT' ? 'text-rose-700 bg-rose-100 shadow-[inset_0_0_0_1px_rgba(225,29,72,0.2)]' : 'text-emerald-700 bg-emerald-100 shadow-[inset_0_0_0_1px_rgba(52,211,153,0.2)]'
                        }`}>
                        {row.tumorClass}
                      </span>
                    </td>
                    <td className="px-6 py-5">
                      <div className="flex items-center gap-3">
                        <div className="w-16 h-1.5 bg-slate-200 rounded-full overflow-hidden">
                          <div className={`h-full ${row.tumorClass.toUpperCase() === 'MALIGNANT' ? 'bg-rose-500' : 'bg-emerald-500'}`} style={{ width: `${row.confidence}%` }}></div>
                        </div>
                        <span className="text-sm font-bold text-slate-700">{row.confidence.toFixed(1)}%</span>
                      </div>
                    </td>
                    <td className="px-6 py-5 text-right">
                      <button
                        onClick={() => setSelectedReport(row)}
                        className="p-2.5 text-blue-600 bg-blue-50 hover:bg-blue-600 hover:text-white rounded-xl transition-all shadow-sm"
                      >
                        <Icons.Reports size={18} />
                      </button>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={6} className="px-6 py-16 text-center text-slate-400/80">
                    <div className="flex flex-col items-center gap-3">
                      <div className="p-4 bg-slate-50 rounded-full mb-2">
                        <Icons.Reports size={32} className="opacity-40" />
                      </div>
                      <p className="font-bold tracking-wide text-slate-500">No archival records found.</p>
                      <p className="text-xs font-light">Uploaded analysis reports will appear here automatically.</p>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default History;
