
import React, { useState } from 'react';
import { TumorClass } from '../types';
import { Icons } from '../constants';
import { useData } from '../contexts/DataContext';

const History: React.FC = () => {
  const { reports } = useData();
  const [selectedReport, setSelectedReport] = useState<any | null>(null);
  const [notification, setNotification] = useState<string | null>(null);

  const showNotification = (message: string) => {
    setNotification(message);
    setTimeout(() => setNotification(null), 3000);
  };

  const handleDownloadPDF = (report: any) => {
    import('jspdf').then(module => {
      const jsPDF = module.default;
      const doc = new jsPDF();

      // Header
      doc.setFillColor(41, 128, 185); // Blue
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.text("BreastCancerAI", 20, 25);
      doc.setFontSize(10);
      doc.text("Diagnostic Analysis Report", 150, 25);

      // Patient Info
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
      doc.text(`Patient ID: ${report.patientId}`, 20, 50);
      doc.text(`Patient Name: ${report.patientName || 'N/A'}`, 20, 60);
      doc.text(`Date: ${report.date}`, 140, 50);
      doc.text(`Report ID: ${report.id}`, 140, 60);

      // Line Divider
      doc.setDrawColor(200, 200, 200);
      doc.line(20, 70, 190, 70);

      // Results
      doc.setFontSize(16);
      doc.setTextColor(report.tumorClass === TumorClass.MALIGNANT ? 200 : 0, report.tumorClass === TumorClass.BENIGN ? 150 : 0, 0);
      doc.text(`Result: ${report.tumorClass.toUpperCase()}`, 20, 90);

      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
      doc.text(`Confidence: ${report.confidence}%`, 140, 90);

      // Findings
      doc.setFontSize(14);
      doc.text("AI Findings:", 20, 110);
      doc.setFontSize(11);
      doc.setTextColor(80, 80, 80);
      const splitText = doc.splitTextToSize(report.explanation || "No explanation provided.", 170);
      doc.text(splitText, 20, 120);

      // Recommendations
      if (report.recommendations && report.recommendations.length > 0) {
        let yPos = 120 + (splitText.length * 5) + 20;
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text("Clinical Recommendations:", 20, yPos);

        doc.setFontSize(11);
        doc.setTextColor(80, 80, 80);
        yPos += 10;
        report.recommendations.forEach((rec: string) => {
          doc.text(`• ${rec}`, 25, yPos);
          yPos += 7;
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by BreastCancerAI. This is an assistive tool and not a final diagnosis.", 20, 280);

      doc.save(`Report_${report.patientId}_${report.date}.pdf`);
      showNotification('PDF downloaded successfully!');
    });
  };

  const handleExportCSV = () => {
    if (reports.length === 0) {
      showNotification("No data to export.");
      return;
    }
    const headers = ['Analysis ID', 'Patient Name', 'Patient ID', 'Date', 'Result', 'Confidence'];
    const csvContent = [
      headers.join(','),
      ...reports.map(row => [row.id, row.patientName, row.patientId, row.date, row.tumorClass, `${row.confidence}%`].join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `oncovision-history-${Date.now()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    showNotification('CSV exported successfully!');
  };

  return (
    <div className="fade-in space-y-6 relative">
      {/* Toast Notification */}
      {notification && (
        <div className="fixed top-4 right-4 bg-blue-600 text-white px-6 py-3 rounded-xl shadow-lg z-50 animate-pulse">
          {notification}
        </div>
      )}

      {/* Report Modal */}
      {selectedReport && (
        <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={() => setSelectedReport(null)}>
          <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full p-6 animate-in slide-in-from-bottom-4" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-start mb-6">
              <div>
                <h3 className="text-xl font-bold text-slate-900">Analysis Details</h3>
                <p className="text-sm text-slate-500">ID: {selectedReport.id}</p>
              </div>
              <button onClick={() => setSelectedReport(null)} className="p-2 hover:bg-slate-100 rounded-full transition-colors">
                <Icons.X size={20} className="text-slate-400" />
              </button>
            </div>

            <div className="space-y-4">
              <div className="bg-slate-50 p-4 rounded-xl">
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="block font-bold text-slate-400 text-xs uppercase tracking-wider">Patient</span>
                    <span className="font-medium text-slate-900">{selectedReport.patientName}</span>
                    <span className="block text-xs text-slate-400">({selectedReport.patientId})</span>
                  </div>
                  <div>
                    <span className="block font-bold text-slate-400 text-xs uppercase tracking-wider">Date</span>
                    <span className="font-medium text-slate-900">{selectedReport.date}</span>
                  </div>
                  <div>
                    <span className="block font-bold text-slate-400 text-xs uppercase tracking-wider">Confidence</span>
                    <span className="font-medium text-slate-900">{selectedReport.confidence.toFixed(3)}%</span>
                  </div>
                </div>
              </div>

              <div className={`p-4 rounded-xl border ${selectedReport.tumorClass === TumorClass.MALIGNANT ? 'bg-red-50 border-red-100' : 'bg-green-50 border-green-100'}`}>
                <span className="block font-bold text-slate-400 text-xs uppercase tracking-wider mb-1">Classification</span>
                <span className={`text-lg font-bold ${selectedReport.tumorClass === TumorClass.MALIGNANT ? 'text-red-700' : 'text-green-700'}`}>
                  {selectedReport.tumorClass}
                </span>
                <p className="text-sm text-slate-600 mt-2">
                  {selectedReport.tumorClass === TumorClass.MALIGNANT
                    ? 'Automated analysis detected patterns consistent with malignancy.'
                    : 'No malignant patterns detected in the analyzed sample.'}
                </p>
                {selectedReport.explanation && (
                  <p className="text-xs text-slate-500 mt-2 italic border-t border-slate-200 pt-2">
                    "{selectedReport.explanation.substring(0, 100)}..."
                  </p>
                )}
              </div>
            </div>

            <div className="flex gap-3 mt-6">
              <button onClick={() => handleDownloadPDF(selectedReport)} className="flex-1 bg-slate-900 text-white py-3 rounded-xl font-bold hover:bg-slate-800 transition-all flex items-center justify-center gap-2 text-sm">
                <Icons.Reports size={18} />
                Download Full PDF
              </button>
              <button onClick={() => setSelectedReport(null)} className="flex-1 bg-white border border-slate-200 text-slate-700 py-3 rounded-xl font-bold hover:bg-slate-50 transition-all text-sm">
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Analysis Archive</h1>
          <p className="text-slate-500">History of all diagnostic scans performed by your team.</p>
        </div>
        <div className="flex gap-2 relative">
          <button
            onClick={handleExportCSV}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-all shadow-lg shadow-blue-200 flex items-center gap-2"
          >
            <Icons.Reports size={16} />
            Export CSV
          </button>
        </div>
      </div>

      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-x-auto overflow-y-hidden">
        <table className="w-full text-left border-collapse min-w-[800px]">
          <thead>
            <tr className="bg-slate-50 border-b border-slate-100">
              <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-widest">Analysis ID</th>
              <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-widest">Patient</th>
              <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-widest">Date</th>
              <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-widest">Result</th>
              <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-widest">Confidence</th>
              <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-widest">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-50">
            {reports.length > 0 ? (
              reports.map((row) => (
                <tr key={row.id} className="hover:bg-slate-50 transition-colors group">
                  <td className="px-6 py-4 font-medium text-slate-900">{row.id}</td>
                  <td className="px-6 py-4 text-slate-500">
                    <p className="font-medium text-slate-700">{row.patientName}</p>
                    <p className="text-xs">{row.patientId}</p>
                  </td>
                  <td className="px-6 py-4 text-slate-500">{row.date}</td>
                  <td className="px-6 py-4">
                    <span className={`text-xs font-bold px-3 py-1 rounded-full ${row.tumorClass.toUpperCase() === 'MALIGNANT' ? 'text-red-700 bg-red-100' : 'text-green-700 bg-green-100'
                      }`}>
                      {row.tumorClass}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <div className="w-12 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                        <div className={`h-full ${row.tumorClass.toUpperCase() === 'MALIGNANT' ? 'bg-red-500' : 'bg-green-500'}`} style={{ width: `${row.confidence}%` }}></div>
                      </div>
                      <span className="text-sm font-bold text-slate-900">{row.confidence}%</span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <button
                      onClick={() => setSelectedReport(row)}
                      className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors border border-transparent hover:border-blue-100"
                    >
                      <Icons.Reports size={18} />
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={7} className="px-6 py-12 text-center text-slate-400">
                  <div className="flex flex-col items-center gap-2">
                    <Icons.Reports size={32} className="opacity-20" />
                    <p>No records found.</p>
                    <p className="text-xs">Uploaded analysis reports will appear here.</p>
                  </div>
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default History;
